Repository steelydylan/react-split-mde, pull requests merged in 2021-04, with the labels that each got.

#6 fix: remove console.log
  src/components/Textarea.tsx
Labels: chore

#7 chore: fix workflow
  .github/workflows/publish.yml
Labels: chore

#8 chore: vup to 1.3.1
  .github/workflows/publish.yml
  README.md
  demo/index.tsx
  package.json
  src/commands/bulletList.ts
  src/commands/orderedList.ts
  src/components/Editor.tsx
  src/components/Textarea.tsx
Labels: release

#9 Fix/list composing
  src/components/Textarea.tsx
Labels: bugfix

#10 fix: composingの調整
  src/components/Textarea.tsx
Labels: bugfix

#11 Hotfix/0.3.2
  package.json
  src/components/Textarea.tsx
Labels: release

#12 chore: suppress removeEventListener error
  src/components/Textarea.tsx
Labels: chore

#13 Hotfix/0.3.3
  package.json
  src/components/Textarea.tsx
Labels: release
